//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneSTools.TechLog.Exporter.ClickHouse.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneSTools.TechLog.Exporter.ClickHouse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE TABLE IF NOT EXISTS Items
        ///(
        ///	DateTime DateTime Codec(Delta, LZ4),
        ///StartTicks Int64 Codec(DoubleDelta, LZ4),
        ///EndTicks Int64 Codec(DoubleDelta, LZ4),
        ///	EventName LowCardinality(String),
        ///	Duration Int64 Codec(DoubleDelta, LZ4),
        ///	PProcessName LowCardinality(String),
        ///	SessionID String Codec(ZSTD),
        ///	TClientID Int32 Codec(DoubleDelta, LZ4),
        ///	TApplicationName LowCardinality(String),
        ///	TComputerName LowCardinality(String),
        ///	TConnectID Int32 Codec(DoubleDelta, LZ4),
        ///	Usr LowCardinality(String),
        ///	Sq [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CreateItemsTable {
            get {
                return ResourceManager.GetString("CreateItemsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE TABLE IF NOT EXISTS LastPositions
        ///(
        ///	Folder String Codec(ZSTD),
        ///	File String Codec(ZSTD),
        ///	Position Int64 Codec(DoubleDelta, LZ4)
        ///)
        ///engine = MergeTree()
        ///ORDER BY (Folder).
        /// </summary>
        internal static string CreateLastPositionsTable {
            get {
                return ResourceManager.GetString("CreateLastPositionsTable", resourceCulture);
            }
        }
    }
}
